### ISSUE TITLE
Make timestamp more readable

### ISSUE THREAD

**Issue by faiyadh-embodyvr** [kvargha/embody-assessment#1]
Can you make the timestamp of posted comments more in a human-readable format? The timestamp reads "2021-07-27T18:22:08.017425Z". Can we make it more human-readable? 

<img width="1680" alt="Screen Shot 2021-07-27 at 11 35 53 AM" src="https://user-images.githubusercontent.com/31267640/127209575-e54b515f-578b-48bd-8ab6-42f7df35cb0f.png">

**Comment by kvargha** [comment]
Changed timestamp to something more readable.

![chrome_L3q54pjflB](https://user-images.githubusercontent.com/35252220/127253721-e54da816-951a-4270-b329-b3df25de1611.png)
