### ISSUE TITLE
Feature missing: "Overlay all the comments made on the waveform with user’s thumbnail"

### ISSUE THREAD

**Issue by faiyadh-embodyvr** [kvargha/embody-assessment#2]
The assignment has a feature request for overlaying posted comments on the waveform w/ user's thumbnail as stated below:

- "Overlay all the comments made on the waveform with the user’s thumbnail. In the first iteration, you can start with a single image for all users. Eventually, you can move to add a thumbnail image with the first letter of username. If there is more than one comment on the same timestamp, you can display the latest one."

This comes with another requirement as follows:

"Allow a user to read the comment along with the username on the timestamps as they hover over the overlaid thumbnails on the waveform."

Can you please look into it?

**Comment by kvargha** [comment]
Implemented
