### ISSUE TITLE
Multiple calls made for GET /api/get/

### ISSUE THREAD

**Issue by faiyadh-embodyvr** [kvargha/embody-assessment#4]
There are multiple calls of GET /api/get when you are on the page. Do we need multiple calls? Are there reasons behind it? 

<img width="1680" alt="Screen Shot 2021-07-27 at 11 54 07 AM" src="https://user-images.githubusercontent.com/31267640/127211524-75e64914-224d-4476-b647-916af8af2308.png">

<img width="1680" alt="Screen Shot 2021-07-27 at 11 54 44 AM" src="https://user-images.githubusercontent.com/31267640/127211630-1fa9fea8-9c60-481f-9eb9-9c04b89a759e.png">

**Comment by kvargha** [comment]
This was because of a state variable in my useEffect causing it to constantly re-render. Fixed.
